### ISSUE TITLE
请问注册登录界面的html应该怎么写呢

### ISSUE THREAD

**Issue by GHddv** [littlecurl/LoginDemo#3]
您好，请问注册登录界面的html应该怎么写呢，之前没有接触过javascript这方面，方便的话能提供下代码学习一下吗，谢谢。

**Comment by littlecurl** [comment]
> 您好，请问注册登录界面的html应该怎么写呢，之前没有接触过javascript这方面，方便的话能提供下代码学习一下吗，谢谢。

我开发的是Android，Web端也不是很熟，可以去看一下慕课网的免费课程：[SpringBoot构建电商秒杀项目（龙虾三少）](https://www.imooc.com/learn/1079)
